all:
	cd 01  &&  $(MAKE)
	cd 03  &&  $(MAKE)
	cd 08  &&  $(MAKE)
	cd 10  &&  $(MAKE)
	cd 12  &&  $(MAKE)
	cd 13  &&  $(MAKE)


.PHONY: clean
clean:
	cd 01  &&  $(MAKE) clean
	cd 03  &&  $(MAKE) clean
	cd 08  &&  $(MAKE) clean
	cd 12  &&  $(MAKE) clean
	cd 13  &&  $(MAKE) clean
