all:
	cd 01  &&  $(MAKE)
	cd 02  &&  $(MAKE)
	cd 03  &&  $(MAKE)
	cd 04  &&  $(MAKE)


.PHONY: clean
clean:
	cd 01  &&  $(MAKE) clean
	cd 02  &&  $(MAKE) clean
	cd 03  &&  $(MAKE) clean
	cd 04  &&  $(MAKE) clean
