all:
	cd 01  &&  $(MAKE)
	cd 03  &&  $(MAKE)
	cd 04  &&  $(MAKE)
	cd 06  &&  $(MAKE)
	cd 07  &&  $(MAKE)


.PHONY: clean
clean:
	cd 01  &&  $(MAKE) clean
	cd 03  &&  $(MAKE) clean
	cd 04  &&  $(MAKE) clean
	cd 06  &&  $(MAKE) clean
	cd 07  &&  $(MAKE) clean
