all:
	cd 01  &&  $(MAKE)
	cd 03  &&  $(MAKE)
	cd 04  &&  $(MAKE)
	cd 06  &&  $(MAKE)
	cd 07  &&  $(MAKE)
	cd 09  &&  $(MAKE)
	cd 10  &&  $(MAKE)
	cd 11  &&  $(MAKE)
	cd 15  &&  $(MAKE)
	cd 16  &&  $(MAKE)
	cd 17  &&  $(MAKE)
	cd 18  &&  $(MAKE)
	cd 19  &&  $(MAKE)


.PHONY: clean
clean:
	cd 01  &&  $(MAKE) clean
	cd 03  &&  $(MAKE) clean
	cd 04  &&  $(MAKE) clean
	cd 06  &&  $(MAKE) clean
	cd 07  &&  $(MAKE) clean
	cd 09  &&  $(MAKE) clean
	cd 10  &&  $(MAKE) clean
	cd 11  &&  $(MAKE) clean
	cd 15  &&  $(MAKE) clean
	cd 16  &&  $(MAKE) clean
	cd 17  &&  $(MAKE) clean
	cd 18  &&  $(MAKE) clean
	cd 19  &&  $(MAKE) clean
