all:
	cd 01  &&  $(MAKE)
	cd 02  &&  $(MAKE)
	cd 03  &&  $(MAKE)
	cd 04  &&  $(MAKE)
	cd 05  &&  $(MAKE)
	cd 07  &&  $(MAKE)
	cd 08  &&  $(MAKE)
	cd 09  &&  $(MAKE)
	cd 10  &&  $(MAKE)
	cd 11  &&  $(MAKE)
	cd 12  &&  $(MAKE)
	cd 13  &&  $(MAKE)


.PHONY: clean
clean:
	cd 01  &&  $(MAKE) clean
	cd 02  &&  $(MAKE) clean
	cd 03  &&  $(MAKE) clean
	cd 04  &&  $(MAKE) clean
	cd 05  &&  $(MAKE) clean
	cd 07  &&  $(MAKE) clean
	cd 08  &&  $(MAKE) clean
	cd 09  &&  $(MAKE) clean
	cd 10  &&  $(MAKE) clean
	cd 11  &&  $(MAKE) clean
	cd 12  &&  $(MAKE) clean
	cd 13  &&  $(MAKE) clean
